version: "3.8"

services:
  django:
    container_name: django
    build: ./
    ports:
      - "4000:4000"
    restart: always
#    volumes:
#      - "./app//mediafiles:/usr/src/mediafiles/"
#      - "./app/staticfil:/usr/src/static/"
    networks:
      - mynet
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16.1-alpine3.18
    container_name: postgresql
    hostname: postgresql
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: "postgresUser"
      POSTGRES_USER: "postgresUser"
      POSTGRES_PASSWORD: "postgresPassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql/postgresql-data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql.conf:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresUser -d postgresUser" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - mynet



networks:
  mynet: