# Generated by Django 5.1.4 on 2024-12-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
    ]
